export default  {
  INDEX:"INDEX",
  DISPATCH_USER:"DISPATCH_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SAVE_FILTERS: "SAVE_FILTERS",
  SAVE_SELECTED_FILTERS: "SAVE_SELECTED_FILTERS",
  SAVE_CART_DETAILS: "SAVE_CART_DETAILS",
  ADD_ENTRY: "ADD_ENTRY",
  SAVE_CURRENT_ENTRY: "SAVE_CURRENT_ENTRY"
}
