export default  {
  INDEX:"INDEX",
  DISPATCH_USER:"DISPATCH_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SAVE_FILTERS: "SAVE_FILTERS",
  SAVE_SELECTED_FILTERS: "SAVE_SELECTED_FILTERS"
}
